"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_env_file = BASE_DIR / ".env"
if _env_file.exists():
    try:
        from dotenv import load_dotenv

        load_dotenv(_env_file)
    except ImportError:
        pass


def _resolve_media_root() -> Path:
    """Usa MEDIA_ROOT do ambiente; se inválido (ex. /data/media em local), usa media/ do projeto."""
    configured = os.environ.get("MEDIA_ROOT", "").strip()
    if configured:
        path = Path(configured)
        try:
            path.mkdir(parents=True, exist_ok=True)
            probe = path / ".django_write_test"
            probe.touch()
            probe.unlink()
            return path
        except OSError:
            pass
    local = BASE_DIR / "media"
    local.mkdir(parents=True, exist_ok=True)
    return local


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", ""
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

_allowed = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()
]
_railway_domain = os.environ.get("RAILWAY_PUBLIC_DOMAIN", "").strip()
if _railway_domain and _railway_domain not in _allowed:
    _allowed.append(_railway_domain)
ALLOWED_HOSTS = _allowed if _allowed else (["*"] if DEBUG else [])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
]

JAZZMIN_SETTINGS = {
    "site_title": "Mesa Brasileira",
    "site_header": "Mesa Brasileira",
    "site_brand": "Mesa Brasileira",
    "site_logo": "home/img/logo-mb-pt.png",
    "login_logo": "home/img/logo-mb-pt.png",
    "site_logo_classes": "img-circle",
    "site_icon": "home/img/logo-mb-pt.png",
    "welcome_sign": "Administração da Mesa Brasileira",
    "copyright": "Mesa Brasileira",
    "search_model": ["auth.User", "home.PedidoMusica"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Site", "url": "/", "new_window": True},
        {"name": "Pedir música", "url": "home:pedir_musica", "new_window": False},
        {"model": "home.PedidoMusica"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "order_with_respect_to": [
        "home",
        "home.PedidoMusica",
        "home.EventoSamba",
        "home.ConfiguracaoHome",
        "auth",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "home.ConfiguracaoHome": "fas fa-sliders-h",
        "home.PedidoMusica": "fas fa-music",
        "home.EventoSamba": "fas fa-compact-disc",
        "home.EventoDestaque": "fas fa-star",
        "home.Produto": "fas fa-tshirt",
        "home.Pedido": "fas fa-shopping-bag",
        "home.SlideHome": "fas fa-images",
        "home.Patrocinador": "fas fa-handshake",
        "home.VideoEvento": "fas fa-video",
        "home.SobrePagina": "fas fa-info-circle",
        "home.Contato": "fas fa-address-card",
        "home.MotivoRejeicao": "fas fa-ban",
        "home.InscricaoPush": "fas fa-bell",
        "home.PerfilUtilizador": "fas fa-id-badge",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "home/css/admin-jazzmin.css",
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "show_theme_chooser": True,
    "changeform_format": "horizontal_tabs",
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-warning",
    "accent": "accent-warning",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "lux",
    "default_theme_mode": "light",
    "button_classes": {
        "primary": "btn-warning",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_database_url = os.environ.get("DATABASE_URL", "").strip()
if _database_url:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-pt'

TIME_ZONE = 'Europe/Lisbon'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
# Servir uploads do volume via Django (Railway). Desative se usar S3/CDN.
SERVE_MEDIA = os.environ.get("SERVE_MEDIA", "true").lower() in ("true", "1", "yes")
# Railway: MEDIA_ROOT=/data/media no volume. Em local, .env com /data/media cai para media/ do projeto.
MEDIA_ROOT = _resolve_media_root()

# Uploads maiores (vídeos) — ajuste conforme o plano Railway.
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024

# Auth: public registration to request songs; team marks the queue
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/pedir-musica/'
LOGOUT_REDIRECT_URL = '/'

# User group name allowed to mark songs as "tocado" on the public page.
# Create this group in /admin/ and add the team users.
MESA_BRASILEIRA_EQUIPE_GROUP_NAME = 'Equipe'

# Loja / checkout
def _env_strip(key: str, default: str = "") -> str:
    return os.environ.get(key, default).strip()


SITE_URL = _env_strip("SITE_URL", "http://127.0.0.1:8000").rstrip("/")
LOJA_TOKEN_EMAIL_HORAS = int(_env_strip("LOJA_TOKEN_EMAIL_HORAS", "48"))
CADASTRO_TOKEN_EMAIL_HORAS = int(_env_strip("CADASTRO_TOKEN_EMAIL_HORAS", "48"))
LOJA_MBWAY_TELEFONE = _env_strip("LOJA_MBWAY_TELEFONE")
LOJA_IBAN = _env_strip("LOJA_IBAN")

_n8n_webhook_url = _env_strip("N8N_WEBHOOK_URL")
_email_host_user = _env_strip("EMAIL_HOST_USER")
_email_backend = _env_strip("EMAIL_BACKEND")

# Produção (Railway): SMTP costuma falhar — use webhook n8n (HTTPS).
if _n8n_webhook_url:
    EMAIL_BACKEND = "home.email_backends.n8n_webhook.N8nWebhookEmailBackend"
    N8N_WEBHOOK_URL = _n8n_webhook_url
    N8N_WEBHOOK_SECRET = _env_strip("N8N_WEBHOOK_SECRET")
    # Header Auth do n8n: Name = N8N_HEADER_USERNAME, Value = N8N_WEBHOOK_SECRET
    N8N_HEADER_USERNAME = _env_strip("N8N_HEADER_USERNAME")
    N8N_WEBHOOK_AUTH_HEADER = _env_strip("N8N_WEBHOOK_AUTH_HEADER")
    N8N_WEBHOOK_AUTH_VALUE = _env_strip("N8N_WEBHOOK_AUTH_VALUE")
    N8N_WEBHOOK_BASIC_USER = _env_strip("N8N_WEBHOOK_BASIC_USER")
    N8N_WEBHOOK_BASIC_PASSWORD = _env_strip("N8N_WEBHOOK_BASIC_PASSWORD")
elif _email_backend:
    EMAIL_BACKEND = _email_backend
elif _email_host_user:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = _env_strip("EMAIL_HOST", "smtp.gmail.com")
try:
    EMAIL_PORT = int(_env_strip("EMAIL_PORT", "587"))
except ValueError:
    EMAIL_PORT = 587
EMAIL_USE_TLS = _env_strip("EMAIL_USE_TLS", "true").lower() in ("true", "1", "yes")
EMAIL_USE_SSL = _env_strip("EMAIL_USE_SSL", "false").lower() in ("true", "1", "yes")
EMAIL_HOST_USER = _email_host_user
EMAIL_HOST_PASSWORD = _env_strip("EMAIL_HOST_PASSWORD")
EMAIL_TIMEOUT = int(_env_strip("EMAIL_TIMEOUT", "30"))

_from_custom = _env_strip("DEFAULT_FROM_EMAIL")
if _from_custom:
    DEFAULT_FROM_EMAIL = _from_custom
elif _email_host_user:
    DEFAULT_FROM_EMAIL = f"Mesa Brasileira <{_email_host_user}>"
else:
    DEFAULT_FROM_EMAIL = "Mesa Brasileira <noreply@mesabrasileira.pt>"

# Destino das mensagens do formulário de contacto (/contato/).
CONTATO_EMAIL = _env_strip("CONTATO_EMAIL")

# Web Push (PWA) — avisos de novos pedidos de música para a equipa.
# Se vazio, as chaves são geradas e guardadas na base de dados.
VAPID_PUBLIC_KEY = _env_strip("VAPID_PUBLIC_KEY")
VAPID_PRIVATE_KEY = _env_strip("VAPID_PRIVATE_KEY")
VAPID_ADMIN_EMAIL = _env_strip("VAPID_ADMIN_EMAIL")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Produção (Railway HTTPS)
_csrf_origins = [
    o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]
if not _csrf_origins and _railway_domain:
    _csrf_origins = [f"https://{_railway_domain}"]
CSRF_TRUSTED_ORIGINS = _csrf_origins

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Jazzmin: popups de objectos relacionados em modal (iframe).
X_FRAME_OPTIONS = "SAMEORIGIN"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
