# Generated by Django 6.0.5 on 2026-06-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('imagem_url', models.URLField(blank=True, help_text='URL externa da imagem (ex.: Instagram) se não enviar ficheiro.')),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento em destaque',
                'verbose_name_plural': 'Eventos em destaque',
                'ordering': ['ordem', '-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='EventoSamba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='samba/')),
                ('imagem_url', models.URLField(blank=True)),
                ('aceita_pedidos', models.BooleanField(default=True, help_text='Permite pedidos de música neste evento.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento de samba',
                'verbose_name_plural': 'Eventos de samba',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('imagem_url', models.URLField(blank=True)),
                ('link_compra', models.URLField(blank=True, help_text='Link para compra ou contacto.')),
                ('destaque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoMusica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.CharField(max_length=200, verbose_name='Música')),
                ('artista', models.CharField(blank=True, max_length=200)),
                ('pedido_por', models.CharField(max_length=120, verbose_name='O seu nome')),
                ('mensagem', models.CharField(blank=True, max_length=300)),
                ('tocado', models.BooleanField(default=False, verbose_name='Já tocámos')),
                ('tocado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='home.eventosamba')),
            ],
            options={
                'verbose_name': 'Pedido de música',
                'verbose_name_plural': 'Pedidos de música',
                'ordering': ['tocado', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VideoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instagram_url', models.URLField(help_text='Link do post ou reel no Instagram.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Imagem de capa do vídeo (pode colar URL do Instagram).')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='home.eventosamba')),
            ],
            options={
                'verbose_name': 'Vídeo de evento',
                'verbose_name_plural': 'Vídeos de eventos',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
