# Generated by Django 6.0.5 on 2026-06-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='patrocinadores/')),
                ('logo_url', models.URLField(blank=True)),
                ('site', models.URLField(blank=True, help_text='Site ou rede social do patrocinador.')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SlideHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('imagem_url', models.URLField(blank=True, help_text='Imagem do slide (recomendado 1920×600 px).')),
                ('tipo', models.CharField(choices=[('evento', 'Evento'), ('propaganda', 'Propaganda')], default='evento', max_length=20)),
                ('link', models.URLField(blank=True, help_text='Link para propaganda ou página externa (se não houver evento).')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(blank=True, help_text='Se escolher um evento, o clique abre a página desse evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='home.eventodestaque')),
            ],
            options={
                'verbose_name': 'Slide do carrossel',
                'verbose_name_plural': 'Slides do carrossel (home)',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
