# Generated by Django 6.0.5 on 2026-06-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_patrocinador_slidehome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_instagram_url', models.URLField(blank=True, help_text='Cole o link de um post ou reel (ex.: https://www.instagram.com/reel/xxxxx/). O Instagram não permite extrair o MP4 — o vídeo aparece com o player oficial incorporado.', verbose_name='Link do vídeo no Instagram')),
            ],
            options={
                'verbose_name': 'Configuração da página inicial',
                'verbose_name_plural': 'Configuração da página inicial',
            },
        ),
    ]
