# Generated by Django 6.0.5 on 2026-06-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_configuracaohome'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaohome',
            name='logo_arquivo',
            field=models.ImageField(blank=True, help_text='Opcional. Se vazio, usa a logo padrão do site (ficheiro estático).', null=True, upload_to='home/intro/', verbose_name='Logo personalizada'),
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='modo_intro',
            field=models.CharField(choices=[('logo', 'Logo'), ('instagram', 'Vídeo do Instagram (incorporado)'), ('video', 'Vídeo enviado (ficheiro no servidor)')], default='logo', max_length=20, verbose_name='O que mostrar ao lado do texto'),
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='video_arquivo',
            field=models.FileField(blank=True, help_text='MP4, WebM ou MOV. Gravado no volume MEDIA_ROOT (Railway).', null=True, upload_to='home/intro/videos/', verbose_name='Vídeo (upload)'),
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='video_poster',
            field=models.ImageField(blank=True, help_text='Imagem exibida antes de dar play (opcional).', null=True, upload_to='home/intro/posters/', verbose_name='Capa do vídeo'),
        ),
        migrations.AlterField(
            model_name='configuracaohome',
            name='video_instagram_url',
            field=models.URLField(blank=True, help_text='Usado quando o modo é «Instagram». Ex.: https://www.instagram.com/reel/xxxxx/', verbose_name='Link do post/reel no Instagram'),
        ),
    ]
