# Generated by Django 6.0.5 on 2026-06-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_configuracaohome_logo_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaohome',
            name='instagram_imagem',
            field=models.ImageField(blank=True, help_text='Opcional. Se enviar, a imagem aparece clicável e abre o link do Instagram (em vez do player incorporado).', null=True, upload_to='home/intro/instagram/', verbose_name='Imagem de capa (Instagram)'),
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='instagram_imagem_url',
            field=models.URLField(blank=True, help_text='Alternativa ao upload — URL externa da imagem.', verbose_name='URL da imagem de capa'),
        ),
    ]
