# Generated by Django 6.0.5 on 2026-06-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_configuracaohome_instagram_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaohome',
            name='instagram_imagem_url',
            field=models.URLField(blank=True, help_text='Opcional. Se vazio, é preenchida automaticamente a partir do link do Instagram (miniatura estilo WhatsApp).', max_length=1000, verbose_name='URL da imagem de capa'),
        ),
        migrations.AlterField(
            model_name='configuracaohome',
            name='video_instagram_url',
            field=models.URLField(blank=True, help_text='Usado quando o modo é «Instagram». Ex.: https://www.instagram.com/reel/xxxxx/', max_length=1000, verbose_name='Link do post/reel no Instagram'),
        ),
        migrations.AlterField(
            model_name='eventodestaque',
            name='imagem_url',
            field=models.URLField(blank=True, help_text='URL externa da imagem (ex.: Instagram) se não enviar ficheiro.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventodestaque',
            name='link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventosamba',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='site',
            field=models.URLField(blank=True, help_text='Site ou rede social do patrocinador.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link_compra',
            field=models.URLField(blank=True, help_text='Link para compra ou contacto.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='slidehome',
            name='imagem_url',
            field=models.URLField(blank=True, help_text='Imagem do slide (recomendado 1920×600 px).', max_length=1000),
        ),
        migrations.AlterField(
            model_name='slidehome',
            name='link',
            field=models.URLField(blank=True, help_text='Link para propaganda ou página externa (se não houver evento).', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoevento',
            name='instagram_url',
            field=models.URLField(help_text='Link do post ou reel no Instagram.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoevento',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Preenchida automaticamente ao guardar o link do Instagram (pré-visualização).', max_length=1000),
        ),
    ]
