# Generated by Django 6.0.5 on 2026-06-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_configuracaohome_instagram_imagem_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomusica',
            name='observacao_equipe',
            field=models.CharField(blank=True, help_text='Nota interna ao marcar como tocada (opcional).', max_length=300, verbose_name='Observação da equipa'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL da logo (ex.: link do Instagram). Ao guardar, a imagem é copiada para o servidor — links do Instagram não funcionam direto no site.', max_length=1000),
        ),
    ]
