# Generated by Django 6.0.5 on 2026-06-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pedidomusica_observacao_equipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidomusica',
            options={'ordering': ['tocado', 'id'], 'verbose_name': 'Pedido de música', 'verbose_name_plural': 'Pedidos de música'},
        ),
        migrations.AlterField(
            model_name='pedidomusica',
            name='observacao_equipe',
            field=models.CharField(blank=True, help_text='Mensagem visível na fila para quem pediu (ex.: já tocamos antes).', max_length=300, verbose_name='Resposta da mesa'),
        ),
    ]
