# Generated by Django 6.0.5 on 2026-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_pedidomusica_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosamba',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Só pode haver um evento ativo. Ao marcar este, os outros são desativados.'),
        ),
    ]
