# Generated by Django 6.0.5 on 2026-06-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_eventosamba_ativo_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodestaque',
            name='destaque',
            field=models.BooleanField(default=True, help_text='Se marcado, aparece na página inicial. Todos os ativos aparecem em Eventos.'),
        ),
    ]
