# Generated by Django 6.0.5 on 2026-06-03 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_eventodestaque_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaohome',
            name='limite_pedidos_em_fila',
            field=models.PositiveIntegerField(default=15, help_text='Na página «Pedir música», quando existir este número de músicas à espera (não tocadas), o formulário de novos pedidos fica bloqueado.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Máximo de pedidos «Em fila»'),
        ),
    ]
