# Generated by Django 6.0.5 on 2026-06-03 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_configuracaohome_limite_fila'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomusica',
            name='marcado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_musica_marcados', to=settings.AUTH_USER_MODEL, verbose_name='Marcado por (membro)'),
        ),
    ]
