# Generated by Django 6.0.5 on 2026-06-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_pedidomusica_marcado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaohome',
            name='pedir_musica_descricao',
            field=models.TextField(blank=True, help_text='Texto exibido abaixo do título em /pedir-musica/ (classe page-hero-lead). Deixe vazio para usar o texto predefinido.', verbose_name='Descrição da página «Pedir música»'),
        ),
    ]
