# Generated by Django 6.0.5 on 2026-06-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_configuracaohome_pedir_musica_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoevento',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Se marcado, o vídeo pode aparecer na página inicial (secção de vídeos).'),
        ),
    ]
