# Generated by Django 5.2.4 on 2026-06-03 15:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_configuracaohome_videos_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('aguarda_email', 'Aguarda confirmação de email'), ('aguarda_pagamento', 'Aguarda pagamento'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='aguarda_email', max_length=20)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=30)),
                ('morada', models.CharField(max_length=300)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=120)),
                ('pais', models.CharField(default='Portugal', max_length=80)),
                ('notas_entrega', models.CharField(blank=True, max_length=500)),
                ('email_confirmado', models.BooleanField(default=False)),
                ('token_confirmacao', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_expira_em', models.DateTimeField()),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('mbway', 'MB Way'), ('transferencia', 'Transferência bancária')], max_length=20)),
                ('referencia_pagamento', models.CharField(blank=True, help_text='Telefone MB Way ou referência indicada pelo cliente.', max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('email_confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido da loja',
                'verbose_name_plural': 'Pedidos da loja',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='requer_tamanho',
            field=models.BooleanField(default=False, help_text='Marque para artigos como camisolas. O cliente deve escolher um tamanho ao adicionar ao carrinho (configure os tamanhos disponíveis abaixo).', verbose_name='Exige escolha de tamanho'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link_compra',
            field=models.URLField(blank=True, help_text='Link externo opcional (a loja usa carrinho e checkout no site).', max_length=1000),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('tamanho', models.CharField(blank=True, max_length=5)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='home.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='home.pedido')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
        migrations.CreateModel(
            name='TamanhoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='home.produto')),
            ],
            options={
                'verbose_name': 'Tamanho do produto',
                'verbose_name_plural': 'Tamanhos do produto',
                'ordering': ['ordem', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'codigo'), name='uniq_produto_tamanho')],
            },
        ),
    ]
