# Generated by Django 5.2.4 on 2026-06-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_loja_ecommerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email_pagamento_confirmado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email «pagamento recebido» enviado em'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguarda_email', 'Aguarda confirmação de email'), ('aguarda_pagamento', 'Aguarda pagamento'), ('pago', 'Pago — a preparar entrega'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='aguarda_email', max_length=20),
        ),
    ]
