# Generated by Django 5.2.4 on 2026-06-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_pedido_email_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaohome',
            name='loja_iban',
            field=models.CharField(blank=True, help_text='IBAN para pagamento por transferência bancária.', max_length=40, verbose_name='IBAN (transferência)'),
        ),
        migrations.AddField(
            model_name='configuracaohome',
            name='loja_mbway_telefone',
            field=models.CharField(blank=True, help_text='Exibido na página de pagamento e confirmação do pedido.', max_length=30, verbose_name='Telefone MB Way'),
        ),
    ]
