# Generated by Django 5.2.4 on 2026-06-04 19:03

from django.db import migrations, models


def preencher_tocado_em(apps, schema_editor):
    PedidoMusica = apps.get_model("home", "PedidoMusica")
    for pedido in PedidoMusica.objects.filter(tocado=True, tocado_em__isnull=True):
        pedido.tocado_em = pedido.criado_em
        pedido.save(update_fields=["tocado_em"])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_configuracao_vendas_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidomusica',
            options={'ordering': ['tocado', 'tocado_em', 'id'], 'verbose_name': 'Pedido de música', 'verbose_name_plural': 'Pedidos de música'},
        ),
        migrations.AddField(
            model_name='pedidomusica',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AlterField(
            model_name='pedidomusica',
            name='tocado_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que a música foi marcada como tocada (ordem na fila).', null=True, verbose_name='Tocada em'),
        ),
        migrations.RunPython(preencher_tocado_em, migrations.RunPython.noop),
    ]
