# Generated by Django 5.2.4 on 2026-06-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_pedidomusica_fila_ordenacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidomusica',
            options={'ordering': ['tocado', 'id'], 'verbose_name': 'Pedido de música', 'verbose_name_plural': 'Pedidos de música'},
        ),
    ]
