# Generated by Django 5.2 on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_pedidomusica_fila_ordem_atualizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidomusica",
            name="rejeitado",
            field=models.BooleanField(
                default=False,
                help_text="Pedido recusado pela mesa (não entra na fila ativa).",
                verbose_name="Rejeitado",
            ),
        ),
        migrations.AddField(
            model_name="pedidomusica",
            name="rejeitado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Rejeitado em"
            ),
        ),
    ]
