# Generated by Django 5.2 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_pedidomusica_rejeitado"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaohome",
            name="contato_descricao",
            field=models.TextField(
                blank=True,
                help_text="Texto abaixo do título em /contato/. Deixe vazio para usar o texto predefinido.",
                verbose_name="Introdução da página «Contato»",
            ),
        ),
        migrations.AddField(
            model_name="configuracaohome",
            name="contato_email",
            field=models.EmailField(
                blank=True,
                help_text="Exibido na página «Contato».",
                max_length=254,
                verbose_name="Email de contacto",
            ),
        ),
        migrations.AddField(
            model_name="configuracaohome",
            name="contato_telefone",
            field=models.CharField(
                blank=True,
                help_text="Exibido na página «Contato».",
                max_length=40,
                verbose_name="Telefone de contacto",
            ),
        ),
        migrations.AddField(
            model_name="configuracaohome",
            name="sobre_descricao",
            field=models.TextField(
                blank=True,
                help_text="Conteúdo principal em /sobre/. Deixe vazio para usar o texto predefinido.",
                verbose_name="Texto da página «Sobre»",
            ),
        ),
    ]
