# Generated by Django 6.0 on 2026-08-19

from django.db import migrations, models


TOPICOS_INICIAIS = [
    {
        "ordem": 1,
        "titulo": "Samba na rua, do jeito que tem que ser.",
        "conteudo": (
            "<p>O nosso projeto nasceu da vontade de fazer aquilo que o samba sempre soube fazer: "
            "<strong>juntar pessoas</strong>.</p>"
            "<p>Mais do que uma apresentação musical, queremos criar encontros. Levar o samba para a "
            "rua, aproximar músicos e público e transformar cada roda num espaço de alegria, amizade, "
            "cultura e celebração.</p>"
        ),
    },
    {
        "ordem": 2,
        "titulo": "Nossa essência",
        "conteudo": (
            "<p>Acreditamos no samba feito perto das pessoas.</p>"
            "<p>Sem distância entre quem toca e quem canta. Aqui, o público também faz parte da roda: "
            "canta, bate palma, dança e ajuda a construir a energia de cada encontro.</p>"
            "<p>Cavaquinho, banjo, pandeiro, surdo, tantan, repique, reco-reco e muitas vozes se "
            "encontram para manter viva uma das maiores expressões da cultura popular brasileira.</p>"
        ),
    },
    {
        "ordem": 3,
        "titulo": "O samba é o nosso ponto de encontro",
        "conteudo": (
            "<p>Nosso repertório passeia por diferentes gerações do samba, celebrando grandes "
            "compositores e intérpretes e mantendo espaço para novas histórias e novas músicas.</p>"
            "<p>Do partido-alto ao samba de roda, dos clássicos que todo mundo conhece às músicas que "
            "merecem ser redescobertas, queremos preservar a essência sem deixar o samba parar no "
            "tempo.</p>"
        ),
    },
    {
        "ordem": 4,
        "titulo": "Mais que música",
        "conteudo": (
            "<p>Para nós, samba é encontro.</p>"
            "<p>É chegar sem conhecer ninguém e terminar cantando junto.</p>"
            "<p>É a palma da mão marcando o ritmo.</p>"
            "<p>É a mesa cercada de amigos.</p>"
            "<p>É a rua virando palco.</p>"
            "<p>É aquele refrão que começa com poucos e, quando percebemos, todo mundo está "
            "cantando.</p>"
            "<p>É isso que queremos construir a cada roda.</p>"
            "<p><strong>Enquanto houver gente para cantar, haverá samba para acontecer.</strong></p>"
            "<p>Vem pra roda.</p>"
        ),
    },
]


def criar_sobre_inicial(apps, schema_editor):
    SobrePagina = apps.get_model("home", "SobrePagina")
    SobreTopico = apps.get_model("home", "SobreTopico")
    SobrePagina.objects.get_or_create(pk=1, defaults={"subtitulo": ""})
    if SobreTopico.objects.exists():
        return
    for dados in TOPICOS_INICIAIS:
        SobreTopico.objects.create(**dados)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_configuracao_sobre_contato"),
    ]

    operations = [
        migrations.CreateModel(
            name="SobrePagina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtitulo",
                    models.CharField(
                        blank=True,
                        help_text="Texto curto no topo da página. Deixe vazio para o texto predefinido.",
                        max_length=300,
                        verbose_name="Subtítulo (abaixo do título)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Página Sobre",
                "verbose_name_plural": "Página Sobre",
            },
        ),
        migrations.CreateModel(
            name="SobreTopico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "conteudo",
                    models.TextField(
                        help_text="HTML básico permitido: <p>, <strong>, <em>, <br>. Use parágrafos separados com tags <p>...</p>.",
                        verbose_name="Conteúdo",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(default=0, verbose_name="Ordem"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Tópico Sobre",
                "verbose_name_plural": "Tópicos Sobre",
                "ordering": ["ordem", "pk"],
            },
        ),
        migrations.RemoveField(
            model_name="configuracaohome",
            name="sobre_descricao",
        ),
        migrations.RunPython(criar_sobre_inicial, migrations.RunPython.noop),
    ]
