# Generated by Django 6.0 on 2026-08-19

import re

from django.db import migrations, models


def html_para_texto(html):
    if not html:
        return ""
    texto = re.sub(r"</p>\s*<p>", "\n\n", html, flags=re.IGNORECASE)
    texto = re.sub(r"<br\s*/?>", "\n", texto, flags=re.IGNORECASE)
    texto = re.sub(r"<[^>]+>", "", texto)
    return texto.strip()


def migrar_topicos_para_campos(apps, schema_editor):
    SobrePagina = apps.get_model("home", "SobrePagina")
    SobreTopico = apps.get_model("home", "SobreTopico")
    pagina, _ = SobrePagina.objects.get_or_create(pk=1)
    campos = [
        "texto_samba_na_rua",
        "texto_nossa_essencia",
        "texto_ponto_encontro",
        "texto_mais_que_musica",
    ]
    topicos = list(SobreTopico.objects.order_by("ordem", "pk"))
    for campo, topico in zip(campos, topicos):
        if topico and topico.conteudo:
            setattr(pagina, campo, html_para_texto(topico.conteudo))
    pagina.save()


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_sobre_pagina_topicos"),
    ]

    operations = [
        migrations.AddField(
            model_name="sobrepagina",
            name="texto_mais_que_musica",
            field=models.TextField(
                blank=True,
                help_text="Texto desta secção. Deixe linha em branco entre parágrafos.",
                verbose_name="Mais que música",
            ),
        ),
        migrations.AddField(
            model_name="sobrepagina",
            name="texto_nossa_essencia",
            field=models.TextField(
                blank=True,
                help_text="Texto desta secção. Deixe linha em branco entre parágrafos.",
                verbose_name="Nossa essência",
            ),
        ),
        migrations.AddField(
            model_name="sobrepagina",
            name="texto_ponto_encontro",
            field=models.TextField(
                blank=True,
                help_text="Texto desta secção. Deixe linha em branco entre parágrafos.",
                verbose_name="O samba é o nosso ponto de encontro",
            ),
        ),
        migrations.AddField(
            model_name="sobrepagina",
            name="texto_samba_na_rua",
            field=models.TextField(
                blank=True,
                help_text="Texto desta secção. Deixe linha em branco entre parágrafos.",
                verbose_name="Samba na rua, do jeito que tem que ser.",
            ),
        ),
        migrations.RunPython(migrar_topicos_para_campos, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="SobreTopico",
        ),
    ]
