# Generated by Django 6.0 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_sobre_campos_fixos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sobrepagina",
            name="subtitulo",
            field=models.TextField(
                blank=True,
                help_text="Texto introdutório da página (primeira secção). Deixe linha em branco entre parágrafos.",
                verbose_name="Introdução",
            ),
        ),
    ]
