# Generated by Django 5.2.4 on 2026-08-19 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_sobre_subtitulo_textfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patrocinador',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiros'},
        ),
        migrations.AlterField(
            model_name='configuracaohome',
            name='contato_email',
            field=models.EmailField(blank=True, help_text='Endereço exibido na página «Contato». O formulário envia para CONTATO_EMAIL (.env).', max_length=254, verbose_name='Email de contacto (página)'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='site',
            field=models.URLField(blank=True, help_text='Site ou rede social do parceiro.', max_length=1000),
        ),
        migrations.CreateModel(
            name='ContatoDiretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=40, verbose_name='Telefone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('configuracao', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='diretores', to='home.configuracaohome')),
            ],
            options={
                'verbose_name': 'Director do projeto',
                'verbose_name_plural': 'Directores do projeto',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
