# Generated by Django 5.2.4 on 2026-08-20 09:27

from django.db import migrations, models


def migrar_contactos_antigos(apps, schema_editor):
    Contato = apps.get_model("home", "Contato")
    ContatoDiretor = apps.get_model("home", "ContatoDiretor")
    ConfiguracaoHome = apps.get_model("home", "ConfiguracaoHome")

    for diretor in ContatoDiretor.objects.all().order_by("ordem", "nome"):
        Contato.objects.create(
            nome=diretor.nome,
            telefone=diretor.telefone or "",
            email="",
            ordem=diretor.ordem,
            ativo=diretor.ativo,
        )

    config = ConfiguracaoHome.objects.filter(pk=1).first()
    if not config:
        return

    email = (getattr(config, "contato_email", None) or "").strip()
    telefone = (getattr(config, "contato_telefone", None) or "").strip()
    if email or telefone:
        ja_existe = Contato.objects.filter(email=email, telefone=telefone).exists()
        if not ja_existe:
            Contato.objects.create(
                nome="Contacto geral",
                telefone=telefone,
                email=email,
                ordem=0,
                ativo=True,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_contato_diretores"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "telefone",
                    models.CharField(blank=True, max_length=40, verbose_name="Telefone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.RunPython(migrar_contactos_antigos, noop_reverse),
        migrations.RemoveField(
            model_name="configuracaohome",
            name="contato_email",
        ),
        migrations.RemoveField(
            model_name="configuracaohome",
            name="contato_telefone",
        ),
        migrations.DeleteModel(
            name="ContatoDiretor",
        ),
    ]
