# Generated by Django 5.2.4 on 2026-08-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_contato_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaohome',
            name='contato_email',
            field=models.EmailField(blank=True, help_text='Destino das mensagens enviadas pelo formulário da página «Contato». Se vazio, usa a variável de ambiente CONTATO_EMAIL.', max_length=254, verbose_name='Email de contacto'),
        ),
    ]
