# Generated by Django 5.2.4 on 2026-08-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_contato_email_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoRejeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Motivo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Motivo de rejeição',
                'verbose_name_plural': 'Motivos de rejeição',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='pedidomusica',
            name='motivo_rejeicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='home.motivorejeicao', verbose_name='Motivo da rejeição'),
        ),
    ]
