# Generated by Django 5.2.4 on 2026-08-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_seed_motivos_rejeicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosamba',
            name='instagram_videos_url',
            field=models.URLField(blank=True, help_text='Caminho/link do Instagram onde estão os vídeos deste evento (ex.: destaque, álbum ou publicação).', max_length=1000, verbose_name='Instagram (vídeos do evento)'),
        ),
    ]
