# Generated by Django 5.2.4 on 2026-08-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_evento_instagram_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventosamba',
            options={'ordering': ['-data'], 'verbose_name': 'Evento pedir música', 'verbose_name_plural': 'Eventos pedir música'},
        ),
        migrations.RemoveField(
            model_name='eventosamba',
            name='instagram_videos_url',
        ),
        migrations.AddField(
            model_name='eventodestaque',
            name='instagram_videos_url',
            field=models.URLField(blank=True, help_text='Caminho/link do Instagram onde estão os vídeos deste evento (ex.: destaque, álbum ou publicação).', max_length=1000, verbose_name='Instagram (vídeos do evento)'),
        ),
    ]
