# Generated by Django 6.0.5 on 2026-08-20 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_evento_destaque_instagram_renomear_samba'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaohome',
            name='audio_roda',
            field=models.FileField(blank=True, help_text='MP3 tocado automaticamente no hero da roda. Se vazio, usa o ficheiro padrão do site. Gravado no volume MEDIA_ROOT (Railway).', null=True, upload_to='home/roda/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='Samba da página inicial (MP3)'),
        ),
    ]
