# Generated by Django 6.0.5 on 2026-08-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_inscricao_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodestaque',
            name='midias_url',
            field=models.URLField(blank=True, help_text='Link externo para fotos e ficheiros do evento (ex.: pasta no Google Drive, Dropbox ou álbum).', max_length=1000, verbose_name='Repositório de mídias'),
        ),
    ]
