# Generated by Django 5.2.4 on 2026-08-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_sobre_quatro_topicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidehome',
            name='mostrar_subtitulo',
            field=models.BooleanField(default=True, help_text='Exibe o subtítulo no banner. Pode ficar só no admin.', verbose_name='Mostrar subtítulo'),
        ),
        migrations.AddField(
            model_name='slidehome',
            name='mostrar_tag',
            field=models.BooleanField(default=True, help_text='Exibe a etiqueta Evento ou Destaque no banner.', verbose_name='Mostrar tag'),
        ),
        migrations.AddField(
            model_name='slidehome',
            name='mostrar_titulo',
            field=models.BooleanField(default=True, help_text='Exibe o título no banner. Pode ficar só no admin.', verbose_name='Mostrar título'),
        ),
    ]
