# Generated by Django 5.2.4 on 2026-08-24 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models



def atribuir_utilizadores_existentes_a_equipe(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")
    grupo, _ = Group.objects.get_or_create(name="Equipe")
    ids = list(User.objects.values_list("pk", flat=True))
    if ids:
        grupo.user_set.add(*ids)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_slidehome_mostrar_legenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomusica',
            name='utilizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_musica', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
        migrations.AlterField(
            model_name='eventodestaque',
            name='midias_url',
            field=models.URLField(blank=True, help_text='Link externo para fotos e ficheiros do evento (ex.: pasta no Google Drive, Dropbox ou álbum).', max_length=1000, verbose_name='Galeria (repositório externo)'),
        ),
        migrations.RunPython(atribuir_utilizadores_existentes_a_equipe, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CadastroEmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expira_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_cadastro', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Token de confirmação de cadastro',
                'verbose_name_plural': 'Tokens de confirmação de cadastro',
            },
        ),
    ]
