# Generated by Django 5.2.4 on 2026-08-24 21:18

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def deduplicar_pedidos_ativos(apps, schema_editor):
    PedidoMusica = apps.get_model("home", "PedidoMusica")
    vistos = set()
    extras = []
    qs = PedidoMusica.objects.filter(
        tocado=False,
        rejeitado=False,
        utilizador_id__isnull=False,
    ).order_by("id")
    for pedido in qs:
        chave = (pedido.evento_id, pedido.utilizador_id)
        if chave in vistos:
            extras.append(pedido.pk)
        else:
            vistos.add(chave)
    if extras:
        PedidoMusica.objects.filter(pk__in=extras).update(
            rejeitado=True,
            rejeitado_em=timezone.now(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0039_perfil_emails_promocionais"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicar_pedidos_ativos, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="pedidomusica",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("rejeitado", False),
                    ("tocado", False),
                    ("utilizador__isnull", False),
                ),
                fields=("evento", "utilizador"),
                name="unico_pedido_ativo_por_utilizador_evento",
                violation_error_message="Este utilizador já tem um pedido ativo neste evento.",
            ),
        ),
    ]
